CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE Konfigurationstabelle (value VARCHAR NOT NULL, key VARCHAR NOT NULL CONSTRAINT Konfigurationstabelle_pk PRIMARY KEY);
CREATE TABLE CUSTOMER (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE TEXT NOT NULL
);
CREATE TABLE WORKSHOP_INFO (
    ID INTEGER PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);
CREATE TABLE CAR (ID TEXT PRIMARY KEY, MODEL TEXT NOT NULL, BRAND TEXT NOT NULL, LICENSEPLATE TEXT NOT NULL, CARSTATUS INTEGER, CUSTOMER_ID INTEGER, FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID));
CREATE TABLE Service (JOB_ID INTEGER PRIMARY KEY, CAR_ID TEXT NOT NULL, JOB_NAME TEXT NOT NULL, STATUS TEXT NOT NULL, TYPE INTEGER NOT NULL, SERVICE_TYPE TEXT NOT NULL, FOREIGN KEY (CAR_ID) REFERENCES CAR (ID));
CREATE TABLE ORDERS (id INTEGER PRIMARY KEY AUTOINCREMENT, CUSTOMER_ID INTEGER NOT NULL REFERENCES CUSTOMER (ID), total REAL NOT NULL CHECK (total >= 0), status TEXT NOT NULL CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'CANCELLED')), order_date TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, service_list TEXT NOT NULL, FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID) ON DELETE CASCADE);
